branch-defaults:
  master:
    environment: node-express-env
    group_suffix: null
environment-defaults:
  node-express-env:
    branch: null
    repository: null
global:
  application_name: Pronoia-Tools-pronoia-coach-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: pro
  repository: null
  sc: git
  workspace_type: Application
